### ISSUE TITLE
data preprocessing code of MELD

### ISSUE THREAD

**Issue by Yuri-Kim** [declare-lab/MELD#18]
Thank you for releasing the baseline code and the feature files. 
Can you open the feature extraction code for speech and text of the MELD dataset?
Thank you.

**Comment by She-yh** [comment]
Hello, I have the same problem. Have you found the answer?

**Comment by She-yh** [comment]
> Thank you for releasing the baseline code and the feature files. Can you open the feature extraction code for speech and text of the MELD dataset? Thank you.

@Yuri-Kim Hi! I have the same problem. Have you found the answer?
