### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/pickles/data_emotion.p'

### ISSUE THREAD

**Issue by elyorman** [declare-lab/MELD#21]
!python baseline.py -classify Emotion -modality bimodal -train
Wanted to run baseline script after having download feature file in ./data/pickles/ dir. But going into this issue. data_emotion.p file is missing and I wonder where I can get it.

**Comment by devamanyu** [comment]
Hi, 

'data_emotion.p' is present in the set of features downloadable from the link https://github.com/declare-lab/MELD#run-the-baseline , kindly check if the file is stored in the correct location as detailed in the running instructions.

regards,
